### ISSUE TITLE
Automation of getting bearer token

### ISSUE THREAD

**Issue by harsanyidani** [li-xl/nuscenes-download#4]
Hey,

Thanks for the great work. 

Automation of getting the bearer token would be useful too in my opinion.

This works for me well, you can consider adding it:
https://github.com/Syzygianinfern0/NuPlan-Download-CLI/blob/main/download_nuplan.py#L11-L33

**Comment by li-xl** [comment]
Thanks for your suggestion!
I have added the login function.
