### ISSUE TITLE
md5 failed

### ISSUE THREAD

**Issue by ShaohuaDong2021** [li-xl/nuscenes-download#5]

**Comment by JonathanWMorris** [comment]
I'm saw that issue too, did you find a solution for it? 
<img width="410" alt="image" src="https://github.com/li-xl/nuscenes-download/assets/65780821/bd7145ca-8cf6-4998-a2b1-da45d8183185">

**Comment by ShaohuaDong2021** [comment]
I did not solve this problem, but after unzip this dataset, everything is fine.

**Comment by JonathanWMorris** [comment]
I see, thank you!

**Comment by ShaohuaDong2021** [comment]
I am not sure if there some issues, if you find that, please let me know. Thank you!

**Comment by li-xl** [comment]
I have updated the md5sum provided by [songshiyu01](https://github.com/songshiyu01).
